# Generated by Django 3.2.6 on 2021-09-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantType',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
